#!/bin/bash
set -euo pipefail
ITS=$'\n\r\t'

usage() {
  cat <<EOF
Usage: $(basename $0) CONFIG_FILE SUBDOMAIN

add a SUBDOMAIN to the CONFIG_FILE

EOF
  exit 1
}

main() {
  parse-args "$@" || usage

  jq --arg arg $SUBDOMAIN \
     '.subdomains = ([$arg, .subdomains[]] | unique)' \
     $CONFIG_FILE
}

parse-args() {
  readonly CONFIG_FILE="${1:-UNSPECIFIED}"
  readonly SUBDOMAIN="${2:-UNSPECIFIED}"

  if grep -q UNSPECIFIED <<<"$CONFIG_FILE\n$SUBDOMAIN" ; then
    return 1
  else
    return 0
  fi
}

main "$@"
